spring:
  application:
    name: great-dogs
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3307/great_dogs?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
    username: root
    password: 123456
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-great-dogs
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true
server:
  port: 18080
logging:
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}){green} %clr([%22thread]){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    web: debug
    org.hibernate.SQL: debug
    org.springframework.web.filter: debug
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    oauth2-redirect-url: /oauth2-redirect.html
    oauth:
      app-name: great-dogs
      #client-id: 
      #client-secret: 
      use-pkce-with-authorization-code-grant: true
      use-basic-authentication-with-access-code-grant: true
  paths-to-match:
  - /api/**